
import React from 'react';

declare const marked: any;

interface SharedReportViewProps {
  reportContent: string;
}

export const SharedReportView: React.FC<SharedReportViewProps> = ({ reportContent }) => {
  const renderedHtml = { __html: marked.parse(reportContent) };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 text-gray-800 dark:text-gray-200 font-sans flex flex-col items-center p-4 sm:p-6 lg:p-8 transition-colors duration-300 fade-in">
      <div className="w-full max-w-4xl mx-auto flex flex-col flex-grow">
        <header className="text-center mb-6 sm:mb-8">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-500 to-teal-500 dark:from-blue-400 dark:to-teal-300">
            Shared Anomaly Report
          </h1>
          <p className="mt-2 text-base sm:text-lg text-gray-600 dark:text-gray-400">
            This is a shared report generated by the OptimaCloud Anomaly Assistant.
          </p>
        </header>

        <div className="mb-6 text-center">
          <p className="text-xs sm:text-sm text-gray-800 dark:text-gray-300 bg-gray-100 dark:bg-gray-800/60 border border-gray-300 dark:border-gray-700/50 rounded-full px-3 py-2 inline-flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 flex-shrink-0" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
            </svg>
            <span>
              <span className="font-semibold">Note:</span> This temporary report link will expire 24 hours after creation.
            </span>
          </p>
        </div>

        <main className="bg-white dark:bg-gray-800/50 backdrop-blur-sm rounded-xl shadow-2xl p-4 sm:p-8 border border-gray-200 dark:border-gray-700 flex-grow">
          <div 
            className="prose dark:prose-invert max-w-none" 
            dangerouslySetInnerHTML={renderedHtml} 
          />
        </main>
        
        <footer className="text-center mt-8 py-4 border-t border-gray-200 dark:border-gray-700">
          <a href="/" className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded-lg transition-colors">
            Create Your Own Report
          </a>
          <p className="text-sm text-gray-500 dark:text-gray-500 mt-4">
            &copy; {new Date().getFullYear()} OptimaCloud. All Rights Reserved.
          </p>
        </footer>
      </div>
    </div>
  );
};